### ISSUE TITLE
Cumulus keeps loading

### ISSUE THREAD

**Issue by oliverZZ** [martinvelez/cumulus#7]
Cumulus just keeps loading and I cannot click on my file

**Comment by Jvlythical** [comment]
Thank you for reporting the issue.  Unfortunately we are releasing a major update and we encountered unexpected problems.  Please bear with us as we work to get Cumulus back up as soon as possible.

**Comment by Jvlythical** [comment]
Sorry for the inconvenience, Cumulus should be back up now.  We are in the process of transferring to a new website, if you would like a sneak-peak please take a look at www.kodethon.com :)
