### ISSUE TITLE
Cumulus not compiling at all

### ISSUE THREAD

**Issue by rosyed** [martinvelez/cumulus#9]
Hi,

I'm writing code in C and my code that is perfectly functional is not compiling at all in cumulus. Can someone please take care of this issue soon. I need to get my homework done.

**Comment by Jvlythical** [comment]
Hello,

I am working on bring it back up. It should be back up in a few minutes.

**Comment by martinvelez** [comment]
Migration guide:

1. In the CDE shell:
`zip -r myFiles.zip` .

2. Download the **myFiles.zip**.

3. Log into http://www.kodethon.com.

4. Drag-n-drop **myFiles.zip**

5. Done!
